// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAcgimwTLSxrMFwLDTMoP3HCgiYfyEBzQ',
    appId: '1:1018596308939:web:2f806fc8939a1d7ee8a84e',
    messagingSenderId: '1018596308939',
    projectId: 'humsaya-app-e822e',
    authDomain: 'humsaya-app-e822e.firebaseapp.com',
    storageBucket: 'humsaya-app-e822e.firebasestorage.app',
    measurementId: 'G-C6TFCBETMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpSoXHpn2zGXTtN6Osgd5GeXWKHFSYL4',
    appId: '1:1018596308939:android:be06fdd6aee01a31e8a84e',
    messagingSenderId: '1018596308939',
    projectId: 'humsaya-app-e822e',
    storageBucket: 'humsaya-app-e822e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJ1LbETLlNX04wtCqXek2u5Ebk8HWIt0',
    appId: '1:1018596308939:ios:7051d088454bb683e8a84e',
    messagingSenderId: '1018596308939',
    projectId: 'humsaya-app-e822e',
    storageBucket: 'humsaya-app-e822e.firebasestorage.app',
    iosBundleId: 'com.example.humsayaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJ1LbETLlNX04wtCqXek2u5Ebk8HWIt0',
    appId: '1:1018596308939:ios:7051d088454bb683e8a84e',
    messagingSenderId: '1018596308939',
    projectId: 'humsaya-app-e822e',
    storageBucket: 'humsaya-app-e822e.firebasestorage.app',
    iosBundleId: 'com.example.humsayaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAcgimwTLSxrMFwLDTMoP3HCgiYfyEBzQ',
    appId: '1:1018596308939:web:476eb009fe7e1b5ce8a84e',
    messagingSenderId: '1018596308939',
    projectId: 'humsaya-app-e822e',
    authDomain: 'humsaya-app-e822e.firebaseapp.com',
    storageBucket: 'humsaya-app-e822e.firebasestorage.app',
    measurementId: 'G-MMG2BNHS9K',
  );
}
